name: Compile Binaries
on:
  push:
    branches: [ none ]

jobs:
  create-release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get version
        run: echo "version=$(jq -r .version build-config.json)" >> $GITHUB_ENV
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          release_name: Release v${{ env.version }}
          draft: false
          prerelease: ${{ contains(env.version, 'beta') || contains(env.version, 'alpha') }}

  build-launcher:
    permissions: write-all
    needs: create-release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: 3.10.6
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r OpenEZ/requirements.txt
        shell: bash

      - name: Build 
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: pyinstaller --onefile OpenEZ/OpenEZ.py
        shell: bash
